### ISSUE TITLE
Redirect neteng.xyz to disnog.org

### ISSUE THREAD

**Issue by rahul-sundaresan** [networking-discord/networking-discord.github.io#14]
**Is your feature request related to a problem? Please describe.**
Older links with xyz tld will not be seen with the same validity of an org tld. Users who use the old domain will not see the new domain

**Describe the solution you'd like**
xyz domain should 301 redirect to the new org domain and not just display the exact same website

**Comment by jrokeach** [comment]
Fully retired neteng.xyz
