### ISSUE TITLE
Policy Change: Nitro Boosters allowed into Education Category

### ISSUE THREAD

**Issue by jrokeach** [networking-discord/networking-discord.github.io#3]
Alright guys, we're trying something new on a trial basis. We'll see how it plays out and your input is valued. We're going to allow folks who Nitro Boost the server into the Education category only, for those who are seeking to become educated enough to figure out the answer to the challenge question. Please don't _just give out_ the answer to the challenge question or obviously this won't work. Rules still apply to them just as everyone else.
Please submit any comments on this change here in comments! You can leave a simple +1 or -1 by adding a reaction to this comment.

**Comment by jrokeach** [comment]
Well, we're not off to a good start:
![image](https://user-images.githubusercontent.com/1076569/63906949-9707a600-c9e7-11e9-98bc-5dab4e1d91a0.png)

**Comment by rahul-sundaresan** [comment]
Why are people with money (nitro boosters) given more preferential treatment than people without any money? Either all new members should be allowed to access education or none of them should. I also think it's a good idea to let new users to have access to education only in case they're new to networking and want to learn more

**Comment by jrokeach** [comment]
This trial was not generally successful; only one user actually took advantage of this, and did so with the intent of immediately violating server rules. As such, I have disabled this permission and will be reverting the guidelines page.
