### ISSUE TITLE
Links to resources can be provided with the intro question

### ISSUE THREAD

**Issue by rahul-sundaresan** [networking-discord/networking-discord.github.io#6]
**Is your feature request related to a problem? Please describe.**
Not everyone joining the discord is a professional and some may want to join just to learn networking, maybe even from scratch. Now if a complete network beginner (like a developer) who's just familiar with application layer protocols gets hit with a network layer question, they may stumble and won't even know where to research the question topic in the first place.

**Describe the solution you'd like**
Assuming we're moving forward with the question bank approach, add a link that helps with researching the answer but does not give the answer outright. Or maybe a list of topics that the user can start researching.

**Describe alternatives you've considered**
I've also considered that users should be given access to #education when they join the server (without the intro question)  and can be granted access to the rest of the server when they pass the NDCNA test 😉 
But this has the potential for increased spam by users who don't read the rules and will clutter up the channel. Perhaps a separate channel where members and non members can interact?

**Comment by jrokeach** [comment]
Superceded by website membership gateway
