### ISSUE TITLE
the website is not reachable over IPv6

### ISSUE THREAD

**Issue by rahul-sundaresan** [networking-discord/networking-discord.github.io#7]
**Is your feature request related to a problem? Please describe.**
The website is not reachable over IPv6

**Describe the solution you'd like**
The website should be reachable over IPv6

**Describe alternatives you've considered**
IPv10 but that is still in the draft stage

**Additional context**
I like IPv6

**Comment by jrokeach** [comment]
Tell GitHub :disappointed:

**Comment by jrokeach** [comment]
Took your suggestion and stuck it behind CloudFlare. IPv6 and SSL are working now.
