### ISSUE TITLE
The website does not automatically redirect to HTTPS

### ISSUE THREAD

**Issue by rahul-sundaresan** [networking-discord/networking-discord.github.io#9]
https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https

**Comment by jrokeach** [comment]
It won't work. Appears we're stumbling on a GitHub bug. It's been stuck on:

> TLS certificate is being provisioned. This may take up to 15 minutes to complete.
> 1 of 3
> Certificate Request Error: Certificate provisioning will retry automatically in a short period, please be patient.

Since moving to the neteng.xyz domain.

Either way, it won't be an issue forever, as we'll move everything to the new site.
